### ISSUE TITLE
GM cannot load Players Save Slots Other than 1

### ISSUE THREAD

**Issue by gavinsimmons** [maxpaulus43/owlbear-shadowdark-character-sheet#37]
As the GM, when a player switches to their 2-5 save slots, I cannot load those characters in my view. Is this a known issue, or possibly user error? (I think I tried everything)

Steps

1. Start owlbear rodeo 2 game as GM
2. Have player join
3. Player loads character sheets from json into their 1st and 2nd save slots
4. Player clicks to display their character sheet in save slot 2 for themselves
5. As GM I click to sync/load players character sheet
6. It loads their character sheet that is in the players save slot 1, even though they are currently viewing their second save slot

**Comment by maxpaulus43** [comment]
Hmm could you list what steps you're taking to try to load a player character sheet? I'm not sure what you mean by this sentence: "players that are not in save slot"

**Comment by gavinsimmons** [comment]
Sorry for the confusion, I updated the original post, and here are steps

1. Start owlbear rodeo 2 game as GM
2. Have player join
3. Player loads character sheets from json into their 1st and 2nd save slots
4. Player clicks to display their character sheet in save slot 2 for themselves
5. As GM I click to sync/load players character sheet
6. It loads their character sheet that is in the players save slot 1, even though they are currently viewing their second save slot

**Comment by maxpaulus43** [comment]
Ahh I see. I opted to allow the GM to view all the character sheets for a player regardless of which sheet the player is looking at. I was thinking that when running a gauntlet or something, the GM might want to view all the players characters.

**Comment by gavinsimmons** [comment]
Ah I see, so as GM I can go to the save slots popup and switch between their character sheets. Thanks for clarifying!
