### ISSUE TITLE
Item Issues

### ISSUE THREAD

**Issue by Gavin-is** [maxpaulus43/owlbear-shadowdark-character-sheet#38]
The playgroup I am in is using the extension, and noticing a few item issues. There may be more, and we can try to go through and QA all of them, but are just a couple:

- Warhammer should be 1 slot (currently 2 slots in extension)
- Crawling Kit should add discrete items to your inventory (each item in the crawling kit can be used up individually)

**Comment by maxpaulus43** [comment]
oh nice catch. i'll fix these this week

**Comment by maxpaulus43** [comment]
opted to just remove the crawling kit gear item. crawling kit is already handled pretty well by shadowdarklings.net
