### ISSUE TITLE
Wrong damage die for Greatswords

### ISSUE THREAD

**Issue by karasikrus** [maxpaulus43/owlbear-shadowdark-character-sheet#40]
If you choose Greatsword as a weapon, it uses d8 damage die instead of d12. The only workaround is to create custom gear, which is not convenient.

**Comment by maxpaulus43** [comment]
good catch. fixed.

**Comment by maxpaulus43** [comment]
fixed this! thanks for the feedback!Max PaulusOn Jun 25, 2023, at 2:07 AM, karasikrus ***@***.***> wrote:﻿
If you choose Greatsword as a weapon, it uses d8 damage die instead of d12. The only workaround is to create custom gear, which is not convenient.
