### ISSUE TITLE
   Dice roll history visible in character sheet                       

### ISSUE THREAD

**Issue by zizazat** [maxpaulus43/owlbear-shadowdark-character-sheet#41]
After using the SD sheet to generate a Notification result, these could be recorded in a Roll History. Perhaps a dice icon in the main icon bar.

Also if possible a configuration value for how long the Notification pop-up is active. 

![image](https://github.com/maxpaulus43/owlbear-shadowdark-character-sheet/assets/48926395/f015e32e-62b2-4381-b34e-9f97f4b107b7)

**Comment by geekxx** [comment]
I'd add that roll history for the players and GM should be visible. As a Gm I often miss initiative rolls for everyone since they pop-up and go away so fast.

**Comment by maxpaulus43** [comment]
this is a good idea. just haven't had time to implement it recently. i'll try to get to it soon

**Comment by maxpaulus43** [comment]
added notifications history, where one can see everyone's rolls

**Comment by maxpaulus43** [comment]
also added a configuration value for notification duration
