### ISSUE TITLE
request: add die type to roll notification pop-up

### ISSUE THREAD

**Issue by trak3r** [maxpaulus43/owlbear-shadowdark-character-sheet#42]
it would be helpful to see what type of die is being rolled.
example, instead of "Ted rolled: 3" show "Ted rolled d20: 3"

**Comment by maxpaulus43** [comment]
good idea! i will add that this week. thanksMax PaulusOn Feb 28, 2024, at 10:03 AM, trak3r ***@***.***> wrote:﻿
it would be helpful to see what type of die is being rolled.
example, instead of "Ted rolled: 3" show "Ted rolled d20: 3"

**Comment by maxpaulus43** [comment]
done
