### ISSUE TITLE
weapon specialization might not be adding to attacks

### ISSUE THREAD

**Issue by trak3r** [maxpaulus43/owlbear-shadowdark-character-sheet#43]
![CleanShot 2024-02-28 at 15 16 12@2x](https://github.com/maxpaulus43/owlbear-shadowdark-character-sheet/assets/2057/cf25efcb-e6d6-4928-ba2b-23a4cbce3d08)

**Comment by maxpaulus43** [comment]
oh good catch. thanks for the clear picture. i will investigate this week!Max PaulusOn Feb 28, 2024, at 12:23 PM, trak3r ***@***.***> wrote:﻿
***@***.*** (view on web)

**Comment by maxpaulus43** [comment]
@trak3r can you attach the exported json for this character?

**Comment by maxpaulus43** [comment]
problem was that shadowdarklings exports the string "Bastard sword", but character sheet expects "Bastard Sword". Fixed.

@trak3r you will have to export your character and reimport the character

**Comment by trak3r** [comment]
fantastic, thanks!
