### ISSUE TITLE
Dice rolls from the character sheet don't show up consistently

### ISSUE THREAD

**Issue by jkwatson** [maxpaulus43/owlbear-shadowdark-character-sheet#44]
Once in a while, I'll see one of my players' dice rolls, but mostly they never pop up in the toast like they used to (this seemed to break about 2 weeks ago with the latest OBR update)

**Comment by maxpaulus43** [comment]
yes i noticed that too recently. could be that OBR changed some apis. i will investigate

**Comment by maxpaulus43** [comment]
I didn't realize that OBR has a broadcast API: https://docs.owlbear.rodeo/extensions/apis/broadcast/

I've been using the wrong API for broadcasting messages. I will fix this week

**Comment by maxpaulus43** [comment]
fixed using the new broadcast API
