### ISSUE TITLE
[Bug] Selecting the same file for "Import JSON" doesn't trigger import

### ISSUE THREAD

**Issue by thomashorta** [maxpaulus43/owlbear-shadowdark-character-sheet#51]
### Steps to reproduce
As a player or a GM, it doesn't matter, follow these steps:

1. Click on the "Options" icon
2. Click on "Import JSON"
3. Select a ShadowDarklings JSON (the sheet should load correctly)
4. Click on Clear Current Save Slot (the sheet should be blank again)
5. Click on "Import JSON"
6. Select the SAME JSON as step 3

### Expected Result
It loads the same file again, filling the player sheet.

### Actual Result
Nothing happens, the sheet is still empty.

### Investigation
It looks like this is normal `input` behavior. 

A solution (described [here](https://stackoverflow.com/a/74233411)) would be to clear the input on click, so selecting a file will always cause a "change" in the input. 

I will implement it soon and push a PR later today.

**Comment by maxpaulus43** [comment]
oh good find.
